apiVersion: v1
kind: Secret
metadata:
  name: discord-openai-secret
  namespace: feavy
type: Opaque
stringData:
  BOT_TOKEN: ${BOT_TOKEN}
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  ALLOWED_GUILDS: ${ALLOWED_GUILDS}
  ENGINE: "gpt-4"
  MAX_TOKENS: "300"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-openai
  namespace: feavy
  labels:
    k8s-app: discord-openai
spec:
  selector:
    matchLabels:
      k8s-app: discord-openai
  template:
    metadata:
      labels:
        k8s-app: discord-openai
        name: discord-openai
    spec:
      containers:
        - name: discord-openai
          image: ${DOCKER_IMAGE}
          envFrom:
            - secretRef:
                name: discord-openai-secret
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        kubernetes.io/hostname: 'oracle-paris'
