# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & Deploy to Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-jars
          path: |
            build/libs

      - uses: feavy/deploy@main
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          GITHUB_USERNAME: feavy
          GITHUB_TOKEN: ${{ secrets.PAT }}
          DOCKERFILE_PATH: .
          DOCKER_IMAGE: discord-openai:latest
          DEPLOYMENT: deployment.yml
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ALLOWED_GUILDS: ${{ secrets.ALLOWED_GUILDS }}
          PLATFORM: arm64

      - name: Restart deployment
        run: kubectl rollout restart deployment discord-openai --namespace feavy
